paths:
    data_path: "/mnt/ushelf_star_th/data/PAI_diptera/image_data_filtered"
    model_path: "/mnt/ushelf_star_th/projects/2023_PAI/2023_PAI_diptera/PAI_diptera" # depends on parameters below
    original_data_path: "/mnt/ushelf_star_th/data/PAI_diptera/image_data"
    prediction_path: "/mnt/ushelf_star_th/projects/2023_PAI/2023_PAI_diptera/PAI_diptera" # depends on parameters below
    results_path: "/mnt/ushelf_star_th/projects/2023_PAI/2023_PAI_diptera/PAI_diptera" # !!! Under results_path must be a folder named "models" and "predictions"
    images_stats_path: "/mnt/ushelf_star_th/data/PAI_diptera/image_stats.csv"
parameters:
    model: resnet18  # efficientnet_b3  #   # stnet
    pretrained: True
    dropout: 0.0
    bit_depth: 8
    epochs: 100
    image_size: 640 # only select image sizes devisible by 32
    learningrate: 0.001
    learningrate_sheduler: 'CosineAnnealingWarmRestarts' #'CosineAnnealingWarmRestarts'  # 'cosine'
    normalization: imagenet  # znorm
    num_classes: 12
    batch_size: 8
    optimizer: 'adam'
    verbose: 0 # verbose 0,1,2 or 3
    plot_trainvalpredictions: False
    seed: 42
