paths:
    data_path: "/../../image_data_filtered"
    model_path: "/../../PAI_diptera"
    original_data_path: "/../../image_data_filtered"
    prediction_path: "/../../PAI_diptera"
    results_path: "/../../PAI_diptera"
    images_stats_path: "/mnt/ushelf_star_th/data/PAI_diptera/image_stats.csv"
parameters:
    model: resnet18  # efficientnetb4 # mobilenetv3_large
    bit_depth: 8
    epochs: 100
    image_size: 640 # only select image sizes devisible by 32
    learningrate: 0.001
    learningrate_sheduler: 'CosineAnnealingWarmRestarts'
    model: resnet18
    normalization: simple
    num_classes: 8
    optimizer: 'adamw'
    verbose: 0 # verbose 0,1,2 or 3
    plot_trainvalpredictions: False
    seed: 99
